### PR TITLE
First logo improvement

### PR DESCRIPTION
**Pull request by nefertiset**
Hi,

just a first improvement of the first logo :) Hope you can appreciate.. alternatively I can make some adjustment if you want, let me know..

Bests!

### CODE REVIEW

**Comment by nefertiset** [comment]
I made a better logo with the right font!! :) sorry for the first I didn't pay the necessary attention to the font..

Byez

**Comment by dbrgn** [comment]
I think it's better than the original one :)

**Comment by astagi** [comment]
I think the same ^^ +1 for this logo..

**Comment by guerrerocarlos** [comment]
I think we should better put the svg in the source code, png gets created in instalation time

**Comment by satanas** [comment]
I've decided to don't make changes on Turpial logo until we have a new working version (2.0), so this request will be closed and reopened later

**Pull request closed without merging**
