### PR TITLE
Few patches I made to install turpial in a proper way

### PR DESCRIPTION
**Pull request by fufler**
While installing turpial in my Archlinux I found some bugs that I decided to fix. Here is a brief overview:
- removed hard-coded paths for i18n files;
- added a hack to install i18n files with only one invocation of setup.py (change/remove my code if you know a better way to achieve this);
- moved TRANSLATORS and AUTHORS files to share/doc/turpial (I think these files should not be placed under /usr);
- removed executable bit from almost every file (why does picture file need an executable bit?).

### CODE REVIEW

**Comment by astagi** [comment]
Nice work man ^^ @satanas will merge your patch soon...

**Comment by satanas** [comment]
Hi @fufler, thanks for your collaboration. 

I'm thinking about merging this changes because this branch is the stable one (freezed) and heavy changes only happen in development branch [1]. Would you like to check it out and see if you can help us? There is a lot of things to do right now, you can check our BTS [2] and work with any pending issue or you can suscribe to our mailing list to discuss any topic about the application or development process.

Again, thanks for your interest and collaboration,

Regards

[1] https://github.com/satanas/Turpial/tree/development
[2] http://dev.turpial.org.ve/projects/turpial/versions/4
[3] http://groups.google.com/group/turpial-dev

**Comment by fufler** [comment]
Hi, @satanas.

The reason why I made patches to the master branch is that i didn't succeed at building the code from the development branch. Here is an output:

``` bash
lx@laptop: ~/git/Turpial % python2 ./setup.py -n build            [development]
running build
running compile_catalog
error: no message catalogs found
```

I think that my changes are minor and that's why may be merged  without a doubt. A Problem with i18n messages should be fixed as soon as possible because current version of Turpial installs w/o these messages at all (at least under ArchLinux, but this issue is not related to distribution, I think). Anyway the final decision is yours.

I'd be glad to participate in Turpial development but it's not possible before you translate the issues list to English :)

**Comment by satanas** [comment]
Hey @fufler,

Maybe I can integrate your changes with a new translation available, in that case we could release a 1.6.8 version. I'll study that possibility.

About the development version you should try again because it has been under heavy changes and now it shouldn't ask for i18n catalogs. About the issues list, you're right. Actually new issues are in English but there are old ones in Spanish. However I encourage you to suscribe to mailing list, there we can discuss about issues and you can start working with some simple tasks in order to know the new code.

Regards

**Comment by satanas** [comment]
@fufler,

Your changes have been merged. I'm going to add the Unity integration to release a full revision of Turpial (1.6.8). Thanks for your help, and I hope to see you around squashing more bugs ;)

Regards

**Pull request closed without merging**
