### PR TITLE
[bugfix] custom_browser is NoneType when not set

### PR DESCRIPTION
**Pull request by Bouska**
Got the following traceback when opening the PreferenceDialog for the first time 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/turpial/ui/qt/main.py", line 278, in show_preferences_dialog
    self.preferences_dialog = PreferencesDialog(self)
  File "/usr/lib/python2.7/site-packages/turpial/ui/qt/preferences.py", line 44, in **init**
    self.browser_page = BrowserPage(base)
  File "/usr/lib/python2.7/site-packages/turpial/ui/qt/preferences.py", line 256, in **init**
    self.command.setText(current_browser)
TypeError: QLineEdit.setText(QString): argument 1 has unexpected type 'NoneType'

The commit fixes the faulty type

### CODE REVIEW

**Comment by satanas** [comment]
Hi, I would like to merge the custom_browser fix but this pull request includes code that touch lang.py, notifications.py and webview.py. Could you separate these changes and open two separated pull requests?

Thanks in advance

**Comment by Bouska** [comment]
Oh sorry, i'm quite new to git and the use of branches. I will fix that :)

**Comment by satanas** [comment]
Great! :)

**Comment by Bouska** [comment]
Discard this pull request and see pull #290 ; the others features/bugfix will come later.

**Pull request closed without merging**
