### PR TITLE
Image Preview window, UI refactor and minor fixes

### PR DESCRIPTION
**Pull request by satanas**
Please check this feature is working properly and merge with development @guerrerocarlos @4ndreaSt4gi

### CODE REVIEW

**Comment by astagi** [comment]
What's that????

**Comment by satanas** [comment]
Sorry, I was trying to update my local branch so you could merge automatically the pull request but I accidentally did the merge :( fack

I want to implement the policy that we discussed a long time ago about updating main repo (turpial repo), and the idea is that we make changes in our personal repos and then pull request against Turpial repo. One of us (not related with the code requested) must analyze and test the code, if everything is ok then merge. Are you agree?

What do you think @guerrerocarlos?

Tonight I will document this procedure in our wiki and will send a couple of mails to the list.

Regards

**Comment by astagi** [comment]
Well so what do we have to do now? :) it's just merged, isn't it?

**Comment by satanas** [comment]
Hahaha yup, I'm sorry :( I did the merge by mistake. But there is a new pull request on libturpial. You should check that XD

**Pull request merged**
