### PR TITLE
Improvements on unrepeat status

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by satanas** [comment]
Merged!

**Comment by astagi** [comment]
Thanks but there's something wrong... I can't see it in the development branch :P

**Comment by satanas** [comment]
Oh! Sorry. I forgot to push. Now you should be able to see it xD

**Comment by astagi** [comment]
Yep merged in local ^^... I will start fetching conversations..

Let's rock bro!

On Wed, Dec 28, 2011 at 12:24 AM, Wil Alvarez
reply@reply.github.com
wrote:

> Oh! Sorry. I forgot to push. Now you should be able to see it xD
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/satanas/Turpial/pull/53#issuecomment-3286546

## 

/*

---
- Use the class below to talk with me *
  *********************************
  */

public class =.4ndrea.Stagi=
{
   public Blog = http://4spills.blogspot.com/ ;
   private Skype = andrea.stagi.2 ;
   private Gtalk = stagi.andrea ;
   private MSN = andreastagi<at>hotmail<dot>com ;
   public Twitter = 4ndreaSt4gi ;
   private Facebook = http://facebook.com/andrea.stagi ;
};

**Comment by satanas** [comment]
Hell yeah bro! \m/ I'm working on autocompletion of usernames on update box :)

**Pull request closed without merging**
